#pragma config(Motor,  motorB,          mRight,        tmotorEV3_Large, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motorC,          mLeft,         tmotorEV3_Large, PIDControl, reversed, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int driveSpeed = 40;
int turnSpeed = 30;

void go_forward(){
	motor[mLeft] = driveSpeed;
	motor[mRight] = driveSpeed;
}

void go_backwards(){
	motor[mLeft] = -driveSpeed;
	motor[mRight] = -driveSpeed;
}

void turn_left(){
	motor[mLeft] = -turnSpeed;
	motor[mRight] = turnSpeed;
}

void turn_right(){
	motor[mLeft] = turnSpeed;
	motor[mRight] = -turnSpeed;
}

task main()
{
	go_forward();
	wait1Msec(1500);
	go_backwards();
	wait1Msec(1500);
	turn_left();
	wait1Msec(1500);
	turn_right();
	wait1Msec(1500);
}
